#!/bin/zsh
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-server-info/#api-group-server-info
source ac_lib `basename $0`

typeset -A Array_sitenames

function populate_Array_sitenames() {
	integer local_Index=0
	typeset local_Line
	cat "$HOME/conf/atlassian_cloud_available_site_names" | sort | while read local_Line; do
		if [ ! -z ${local_Line} ]; then
			Array_sitenames+=([${local_Index}]=${local_Line})
			local_Index+=1
		fi
	done
}

function isExistsSiteName() {
  if [ ! -z $1 ]; then
  	# FIXME does this work when only wiki is an active product?
    http_return_code=`curl -i -s -X GET --url "https://$1.atlassian.net/rest/api/3/serverInfo" ${ac_AUTH} ${acHA_JSON} | grep "^HTTP" | awk '{print $2}'`
    if [ ${http_return_code} -eq 200 ]; then
      return 0
    else
    	return 1
    fi
  fi
}

populate_Array_sitenames

if [ -z $1 ]; then
	# enter interactive mode
	integer maxIndex=${#Array_sitenames[@]}-1
	for index_Sitename in {0..${maxIndex}}; do
		printf "%2d" ${index_Sitename}
		if [[ ${ac_SITE_NAME} == ${(v)Array_sitenames[${index_Sitename}]} ]]; then
			printf "*"
		else
			printf " "
		fi
		printf "- %s" ${(v)Array_sitenames[${index_Sitename}]}
		printf "\n"
	done
	vared -p "Activate project: " -c temp_User_Response
	if [[ ${temp_User_Response} =~ '^[0-9]+$' ]]; then
		echo ${(v)Array_sitenames[${temp_User_Response}]} > $HOME/conf/atlassian_cloud_site_name
	fi
	unset temp_User_Response
	ac_lib env
	exit
fi

case $1 in
"help")
  printf "\nHelp for %s commands:\n\n" $(basename "$0")
  printf "%s\t\t\tinteractive mode\n" $(basename "$0")
  printf "%s <siteName>\tmakes <siteName> the active site\n" $(basename "$0")
  ;;
 *)
	for sitename in ${(v)Array_sitenames}; do
		if [[ $1 == ${sitename} ]]; then
			echo $1 > $HOME/conf/atlassian_cloud_site_name
			exit
		fi
	done
	isExistsSiteName $1
	if [ $? -eq 0 ]; then
		echo $1 >> $HOME/conf/atlassian_cloud_available_site_names
		echo $1 > $HOME/conf/atlassian_cloud_site_name
	else
		printf "unable to access %s.\n" $1
	fi
esac
