#!/bin/zsh
source acp_lib `basename $0`

typeset -A commandUsages
commandUsages=([expandnames]="%s:\tjson output with expanded names for an issueIdOrKey.\n\t\tArguments: <issueIdOrKey>\n")

integer -r maxResults=50
integer recordCount
integer numPages

case ${1:l} in
"expandnames")
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-get
  if [ ! -z $2 ]; then
    issueIdOrKey=$2
    curl -s -X GET --url "${acp_URL_JIRA3}issue/${issueIdOrKey}?expand=names" -u "${acp_AUTH}" -H "${acp_HA_JSON}" | jq  
  else
    printf ${commandUsages[${1:l}]} ${(k)commandUsages[${1:l}]}
  fi
  ;;

"help")
  printf "\nHelp for %s commands:\n\n" $(basename "$0")
  for command commandUsage in ${(kv)commandUsages}; do
    printf ${commandUsage} ${command}
    printf "\n"
  done
  printf "%s - usage examples:\n" $(basename "$0")
  ;;

*)
  $(basename "$0") help
  ;;
esac
