#!/bin/zsh
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-server-info/#api-group-server-info
source ac_lib `basename $0`
typeset -A commandUsages
commandUsages+=([csv]="%s:\t\texports licensing information in csv format.\n\t\tArguments: none\n")

typeset -r availableSites="$HOME/conf/atlassian_cloud_available_site_names"

case $1 in
"listKeys")
  curl -s -X GET --url "${ac_url}instance/license" -u "${ac_user}" -H  "${h_a_json}" | jq -r '.applications[0] | keys_unsorted | .[]'
  ;;

"csv")
  printf "sitename,JSW,JSM,JWM\n"
  cat ${availableSites} | while read sitename; do
    site_restUrl="https://${sitename}.atlassian.net/rest/api/3/instance/license"
    http_response=`curl -i -s -X GET --url "${site_restUrl}" -u ${ac_user} -H ${h_a_json}`
    http_return_code=`echo $http_response | grep "^HTTP" | awk '{print $2}'`
    json_response=`echo $http_response | grep -E "^{"`
    if [ ${http_return_code} -eq 200 ]; then
      applications=(`echo ${json_response} | jq -r '.applications[] | join("=")'`)
      JSW="-"
      JSM="-"
      JWM="-"
      for app in ${applications}; do
        appName=`echo ${app} | awk -F "=" {'print $1'}`
        appLicense=`echo ${app} | awk -F "=" {'print $2'}`
        case ${appName} in
        "jira-software")
          JSW=${appLicense}
          ;;
        "jira-servicedesk")
          JSM=${appLicense}
          ;;
        "jira-core")
          JWM=${appLicense}
          ;;
        esac
      done
      printf "%s,%s,%s,%s\n" ${sitename} ${JSW} ${JSM} ${JWM}
    fi
    if [ ${http_return_code} -ge 400 ]; then
      errorMessage=`echo ${json_response} | jq -r '.message'`
      printf "%s-%u-%s,,,\n" ${sitename} ${http_return_code} ${errorMessage}
    fi
  done
  ;;

"help")
  printf "\nHelp for %s commands:\n\n" $(basename "$0")
  for command commandUsage in ${(kv)commandUsages}; do
    printf ${commandUsage} ${command}
    printf "\n"
  done
  printf "%s - usage examples:\n" $(basename "$0")
  printf "\t%s csv | xsv table\n" $(basename "$0")
  printf "\tajcLicenses csv > ajcLicenses.csv; ajcServerInfo csv > ajcServerInfo.csv; xsv join sitename ajcLicenses.csv sitename ajcServerInfo.csv | xsv select sitename,JSW,JSM,JWM,title,locale | xsv table\n"
  ;;

*)
  $(basename "$0") help
  ;;
esac
