#!/bin/zsh
source acp_lib `basename $0`
declare -a available_keywords=("load" "csv" "set" "selected")
if [[ -z $1 ]]; then; user_keyword="hugo"; else; user_keyword=$1; fi
if ! is_keyword_valid ${user_keyword} ${available_keywords[@]}; then; exit 0; fi

case $1 in
"load")
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-project-avatars/#api-rest-api-3-project-projectidorkey-avatar2-post
  if [ -z $2 ] || [ -z $3 ]; then
    print_command_usage $1 "<projectIdOrKey> <avatarFlenameJPEG_GIF_PNG>"
    exit
  fi
  ProjectIdOrKey=$2
  curl -s -X POST --url "${acp_URL_JIRA3}project/${ProjectIdOrKey}/avatar2" -u "${acp_AUTH}" -H "${acp_HAT_NOC}" -H "${acp_HCT_PNG}" --data-binary @${3}
  ;;

"csv")
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-project-avatars/#api-rest-api-3-project-projectidorkey-avatars-get
  if [ -z $2 ]; then
    print_command_usage $1 "<ProjectIdOrKey>"
    exit
  fi
  ProjectIdOrKey=$2
  http_response=`curl -s -X GET --url "${acp_URL_JIRA3}project/${ProjectIdOrKey}/avatars" -u "${acp_AUTH}" -H "${acp_HA_JSON}" | jq -r '.custom[] | [.id, .isSelected ] | @csv'`
  echo ${http_response}
  ;; 

"set")
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-project-avatars/#api-rest-api-3-project-projectidorkey-avatar-put
if [ -z $2 ] || [ -z $3 ]; then
    print_command_usage $1 "<projectIdOrKey> <avatarId>"
    exit
  fi
  ProjectIdOrKey=$2
  avatarId=$3
  curl -s -X PUT --url "${acp_URL_JIRA3}project/${ProjectIdOrKey}/avatar" -u "${acp_AUTH}" -H "${acp_HA_JSON}" -H "${acp_HCT_JSON}" --data "$(jq -n --arg avatarId $avatarId '{"id": $avatarId }')"
  ;;

"selected")
  if [ -z $2 ]; then
    print_command_usage $1 "<ProjectIdOrKey>"
    exit
  fi
  ProjectIdOrKey=$2
  http_response=`curl -s --X GET --url "${acp_URL_JIRA3}project/$2/avatars" -u "${acp_AUTH}" -H "${acp_HA_JSON}" | jq -r '.system + .custom | .[] | select(.isSelected).id'`
  echo ${http_response}
  ;;
esac
