#!/bin/zsh
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-server-info/#api-group-server-info
#
source acp_lib `basename $0`
typeset -A commandUsages
commandUsages+=([json]="%s:\t\texports serverInfo for available sites in json format.\n\t\tArguments: none\n")
commandUsages+=([csv]="%s:\t\texports serverInfo for available sites in csv format.\n\t\tArguments: none\n")

case $1 in
"csv")
  printf "sitename,version,buildNumber,buildDate,title,locale\n"
  cat "$HOME/conf/atlassian_cloud_available_site_names" | while read sitename; do
    eval $(printf "curl -s -X GET --url \"%s\" -u %s -H %s" "https://${sitename}.atlassian.net/rest/api/3/serverInfo" ${ac_user} ${h_a_json}) | \
    jq -r --arg sitename ${sitename} '[ $sitename, .version, .buildNumber, .buildDate[0:10], .serverTitle, .defaultLocale.locale ] | @csv'
  done
  ;;
"json")
  cat "$HOME/conf/atlassian_cloud_available_site_names" | while read sitename; do
    eval $(printf "curl -s -X GET --url \"%s\" -u %s -H %s" "https://${sitename}.atlassian.net/rest/api/3/serverInfo" ${ac_user} ${h_a_json}) | jq
  done
  ;;
"help")
  printf "\nHelp for %s commands:\n\n" $(basename "$0")
  for command commandUsage in ${(kv)commandUsages}; do
    printf ${commandUsage} ${command}
    printf "\n"
  done
  printf "%s - usage examples:\n" $(basename "$0")
  printf "\t%s csv | xsv table\n" $(basename "$0")
  ;;

*)
  $(basename "$0") help
  ;;
esac