#!/bin/zsh
# based on https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-info/#api-group-info
source acp_lib `basename $0`

curl -s -X GET --url "${acp_URL_SD}info" -u "${acp_AUTH}" -H "${acp_HA_JSON}" | jq 
