#!/bin/zsh
source acp_lib `basename $0`
declare -a available_keywords=("count" "getids" "csv")
if [[ -z $1 ]]; then; user_keyword="hugo"; else; user_keyword=$1; fi
if ! is_keyword_valid ${user_keyword} ${available_keywords[@]}; then; exit 0; fi

getids()
{
curl -s -X GET --url "${acp_URL_JIRA3}avatar/project/system" -u "${acp_AUTH}" -H "${acp_HA_JSON}" | jq -r '.system[].id'
}

case $1 in
"count")
  getids | wc -l
  ;;
"getids")
  getids
  ;;
"csv")
  typeset -a projectSystemAvatarIds
  projectSystemAvatarIds=(`getids`)
  for projectSystemAvatarId in ${projectSystemAvatarIds}; do
    avatarTitle=`curl -s -X GET --url "${acp_URL_JIRA3}universal_avatar/view/type/project/avatar/$n" -u "${acp_AUTH}" | htmlq -t 'title'`
    printf "%s,%s,%s\n" ${projectSystemAvatarId} ${avatarTitle} "${acp_URL_JIRA3}universal_avatar/view/type/issuetype/avatar/${projectSystemAvatarId}"
  done
  ;;
esac